version: 1

update_configs:
  - package_manager: javascript
    directory: /
    update_schedule: monthly
    ignored_updates:
      - match:
          dependency_name: "@types/node"
    default_labels:
      - "type: deps"
    commit_message:
      prefix: fix
      prefix_development: chore
      include_scope: true
